// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwvpcuoikxnqjmzzikkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dnBjdW9pa3hucWptenppa2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNTcyOTcsImV4cCI6MjA1MTkzMzI5N30.m9KB5lIOhq4k-mq_O71VOp43ldCEkWWhFLRTtN7TE7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);